<img src="https://drive.google.com/uc?id=1mjMsKVMkSeZ68cAZenxBYByg5-Xb7vRM" />

### Contents
<ul>
    <li><a href='#1'>What is PyTorch?</a></li>
    <li><a href='#2'>What is tensor</a></li>
    <li><a href='#3'>What is CUDA</a></li>
    <li><a href='#4'>Creating a dataset</a></li>
    <li><a href='#5'>DataLoaders</a></li>
    <li><a href='#6'>Transforms</a></li>
    <li><a href='#7'>Creating a model</a></li>    
</ul>

<div id='1'><h2>What is PyTorch?</h2></div>
<p>
PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab. It is free and open-source software released under the Modified BSD license.
<br />
Click <a href="https://pytorch.org/">here</a> for more information.


</p>

In [1]:
import numpy as np 
import torch
import os
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn

<div id='2'><h2>What is tensor?</h2></div>
A PyTorch Tensor is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic n-dimensional array to be used for arbitrary numeric computation. ... To run operations on the GPU, just cast the Tensor to a cuda datatype.
<br />
Click <a href="https://pytorch.org/">here</a> for more iinformation.


In [ ]:
torch.zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand((5, 4))

tensor([[0.0361, 0.5394, 0.7980, 0.8401],
        [0.0094, 0.5661, 0.0535, 0.7751],
        [0.1875, 0.1072, 0.9954, 0.3796],
        [0.7284, 0.2033, 0.0394, 0.0366],
        [0.5495, 0.5868, 0.7458, 0.2909]])

In [ ]:
torch.from_numpy(np.zeros((2, 3)))

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

<div id='3'><h2>What is CUDA?</h2></div>

CUDA is a parallel computing platform and programming model developed by Nvidia for general computing on its own GPUs (graphics processing units). CUDA enables developers to speed up compute-intensive applications by harnessing the power of GPUs for the parallelizable part of the computation.

While there have been other proposed APIs for GPUs, such as OpenCL, and there are competitive GPUs from other companies, such as AMD, the combination of CUDA and Nvidia GPUs dominates several application areas, including deep learning, and is a foundation for some of the fastest computers in the world.



In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [ ]:
zeros = torch.zeros((2, 3))

# model.to(device)

zeros_gpu = zeros.to(device)

model(zeros_gpu)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

<div id='4'><h2>Creating Dataset</h2></div>


In [ ]:
class FaceLandmarksDataset(Dataset):
    def __init__(self, csv_file, root_dir, transform=None):
        self.landmarks_frame = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.landmarks_frame)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        img_name = os.path.join(self.root_dir,
                                self.landmarks_frame.iloc[idx, 0])
        image = io.imread(img_name)
        landmarks = self.landmarks_frame.iloc[idx, 1:]
        landmarks = np.array([landmarks])
        landmarks = landmarks.astype('float').reshape(-1, 2)
        sample = {'image': image, 'landmarks': landmarks}

        if self.transform:
            sample = self.transform(sample)

        return sample

<div id='5'><h2>Data Loaders</h2></div>
Combines a dataset and a sampler, and provides an iterable over the given dataset. The DataLoader supports both map-style and iterable-style datasets with single- or multi-process loading, customizing loading order and optional automatic batching (collation) and memory pinning.

In [ ]:
dataloader = DataLoader(transformed_dataset, batch_size=4,
                        shuffle=True, num_workers=4)

<div id='5'><h2>Transforms</h2></div>
One issue we can see from the above is that the samples are not of the same size. Most neural networks expect the images of a fixed size. Therefore, we will need to write some preprocessing code. 

In [ ]:
# composed = transforms.Compose([Rescale(256),
#                                RandomCrop(224)])

# tsfm = Transform(params)
# transformed_sample = tsfm(sample)

<div id='6'><h2>Models</h2></div>

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [ ]:
class MLP(nn.Module):
    def __init__(self, n_inputs):
        super(MLP, self).__init__()
        self.layer = Linear(n_inputs, 1)
        self.activation = Sigmoid()
 
    def forward(self, X):
        X = self.layer(X)
        X = self.activation(X)
        return X

<hr />

### About the author

`Name`: Erfan Asadi
<br />
`Email`: erfanasadi.ce@gmail.com
<br />
`Linkedin`: https://www.linkedin.com/in/erfan-asadi-9b64b9163/
<br />
`GitHub`: https://github.com/ErfanAsadi
<br />
<hr />